name: example
description: Example project using slang.

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=2.17.0-266.8.beta <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  slang:
    path: ..
  slang_flutter:
    path: ../../slang_flutter
  flutter_localizations: # add this
    sdk: flutter
  cupertino_icons: ^1.0.2

dev_dependencies:
  build_runner: any # and this

flutter:
  uses-material-design: true