name: example
description: Example project using slang.

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=2.17.0-266.8.beta <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  slang: ^2.0.0-dev.0 # add this
  slang_flutter: ^2.0.0-dev.0 # add this
  flutter_localizations: # add this
    sdk: flutter
  cupertino_icons: ^1.0.2

flutter:
  uses-material-design: true