# https://pub.dartlang.org/packages/build_config
builders:
  slang_build_runner:
    import: 'package:slang_build_runner/slang_build_runner.dart'
    builder_factories: ['i18nBuilder']
    build_extensions: {'.i18n.json': ['.g.dart']}
    build_to: source
    auto_apply: root_package
