name: slang_build_runner
description: build_runner integration for slang
version: 2.0.0-dev.0
repository: https://github.com/Tienisto/slang

environment:
  sdk: ">=2.17.0 <3.0.0"

dependencies:
  build: ^2.2.1
  glob: ^2.0.2
  slang: ^2.0.0
