name: slang_build_runner
description: build_runner integration for slang
version: 2.3.0
repository: https://github.com/Tienisto/slang

environment:
  sdk: ">=2.17.0 <3.0.0"

dependencies:
  build: ^2.2.1
  glob: ^2.0.2

  # Use tight version to ensure that all features are available
  slang: '>=2.3.0 <2.4.0'
