# https://pub.dartlang.org/packages/build_config
builders:
  i18nBuilder:
    import: 'package:fast_i18n/src/builder.dart'
    builder_factories: ['i18nBuilder']
    build_extensions: {'.i18n.json': ['.g.dart']}
    build_to: source
    auto_apply: root_package
