name: slang_flutter
description: Flutter support for slang
version: 2.0.0
repository: https://github.com/Tienisto/slang

environment:
  sdk: ">=2.17.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  slang: ^2.0.0
