name: slang_flutter
description: Flutter support for slang
version: 1.0.0-dev.0
repository: https://github.com/Tienisto/flutter-fast-i18n

environment:
  sdk: ">=2.17.0-266.8.beta <3.0.0"

dependencies:
#  slang: ^1.0.0-dev.0
  slang:
    path: ../slang
  flutter:
    sdk: flutter
