name: fast_i18n_flutter
description: Flutter support for fast_i18n
version: 6.0.0-dev.3
repository: https://github.com/Tienisto/flutter-fast-i18n

environment:
  sdk: ">=2.17.0-266.7.beta <3.0.0"

dependencies:
#  fast_i18n: ^6.0.0-dev.4
  fast_i18n:
    path: ../fast_i18n
  flutter:
    sdk: flutter
