name: fast_i18n_flutter
description: Flutter support for fast_i18n
version: 1.0.0
repository: https://github.com/Tienisto/flutter-fast-i18n

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:

dev_dependencies:
